apiVersion: 1

datasources:
  - name: Prometheus   # <-- Matches the 'Prometheus' keyword we just replaced in your JSON!
    type: prometheus
    url: http://gateway-prometheus:9090
    isDefault: true
    access: proxy
    editable: true